#!/usr/bin/env bash

set -euo pipefail

resolve_script_path() {
  local source="$1"
  local directory=""
  local target=""
  while [[ -h "${source}" ]]; do
    directory="$(cd -P "$(dirname "${source}")" && pwd)"
    target="$(/usr/bin/readlink "${source}")"
    if [[ "${target}" == /* ]]; then
      source="${target}"
    else
      source="${directory}/${target}"
    fi
  done
  printf '%s' "${source}"
}

SOURCE_PATH="$(resolve_script_path "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(cd -P "$(dirname "${SOURCE_PATH}")" && pwd)"

DEFAULT_DB_PATH="${SCRIPT_DIR}/tests/test_db.sqlite"
CONFIG_FILE_NAME=".moneywizrc"
CONFIG_DB_PATH=""
CURRENT_REAL_DB_PATH="${HOME}/Library/Containers/com.moneywiz.personalfinance-setapp/Data/Library/Application Support/MoneyWiz_iCloud.sqlite"
LEGACY_REAL_DB_PATH="${HOME}/Library/Containers/com.moneywiz.personalfinance-setapp/Data/Documents/.AppData/ipadMoneyWiz.sqlite"
BUNDLE_HOST="${SCRIPT_DIR}/../../MacOS/MoneyWizTools"
BUNDLED_PY="${SCRIPT_DIR}/python/venv/bin/python"
BUNDLE_INFO_PLIST="${SCRIPT_DIR}/../../Info.plist"
SOURCE_INFO_PLIST="${SCRIPT_DIR}/scripts/MoneyWizTools-Info.plist"
IS_BUNDLED=0

print_version() {
  local info_plist="${SOURCE_INFO_PLIST}"
  local version=""
  if [[ -x "${BUNDLE_HOST}" ]]; then
    info_plist="${BUNDLE_INFO_PLIST}"
  fi
  if [[ -r "${info_plist}" ]]; then
    version="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "${info_plist}" 2>/dev/null || true)"
  fi
  printf 'moneywiz %s\n' "${version:-unknown}"
}

for argument in "$@"; do
  if [[ "${argument}" == "--version" || "${argument}" == "-V" ]]; then
    print_version
    exit 0
  fi
done

trim_ws() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "${value}"
}

discover_real_db_path() {
  local candidate=""
  for candidate in "${CURRENT_REAL_DB_PATH}" "${LEGACY_REAL_DB_PATH}"; do
    if [[ -f "${candidate}" ]]; then
      printf '%s' "${candidate}"
      return
    fi
  done
  printf '%s' "${CURRENT_REAL_DB_PATH}"
}

DEFAULT_REAL_DB_PATH="$(discover_real_db_path)"

read_config_file() {
  local file="$1"
  [[ -f "${file}" ]] || return 1
  while IFS= read -r line || [[ -n "${line}" ]]; do
    line="${line%%#*}"
    line="$(trim_ws "${line}")"
    [[ -z "${line}" || "${line}" != *"="* ]] && continue
    local key="${line%%=*}"
    local value="${line#*=}"
    key="$(trim_ws "${key}")"
    value="$(trim_ws "${value}")"
    if [[ "${value}" == \"*\" && ${#value} -ge 2 ]]; then
      value="${value:1:${#value}-2}"
    elif [[ "${value}" == \'*\' && ${#value} -ge 2 ]]; then
      value="${value:1:${#value}-2}"
    fi
    if [[ "${value}" == \~/* ]]; then
      value="${HOME}/${value:2}"
    fi
    case "$(printf '%s' "${key}" | tr '[:upper:]' '[:lower:]')" in
      db_path)
        CONFIG_DB_PATH="${value}"
        ;;
      *)
        ;;
    esac
  done <"${file}"
}

generate_home_config() {
  local config_path="${HOME}/${CONFIG_FILE_NAME}"
  if [[ -f "${config_path}" ]]; then
    echo "Config already exists at ${config_path}; leaving as-is."
    return
  fi
  local db_line=""
  local note=""
  if [[ -f "${DEFAULT_REAL_DB_PATH}" ]]; then
    db_line="db_path=${DEFAULT_REAL_DB_PATH}"
  else
    db_line="# db_path=${DEFAULT_REAL_DB_PATH}"
    note="# Update this path and uncomment it once the database exists."
  fi
  {
    echo "# MoneyWiz Tools configuration generated by --setup"
    echo "${db_line}"
    [[ -n "${note}" ]] && echo "${note}"
  } >"${config_path}"
  echo "Wrote ${config_path}"
}

run_setup() {
  generate_home_config
  echo "Setup complete."
}

HOME_CONFIG_FILE="${HOME}/${CONFIG_FILE_NAME}"
LOCAL_CONFIG_FILE="${SCRIPT_DIR}/${CONFIG_FILE_NAME}"
if [[ -f "${HOME_CONFIG_FILE}" ]]; then
  read_config_file "${HOME_CONFIG_FILE}"
fi
if [[ -z "${CONFIG_DB_PATH}" && -f "${LOCAL_CONFIG_FILE}" ]]; then
  read_config_file "${LOCAL_CONFIG_FILE}"
fi

if [[ -x "${BUNDLED_PY}" ]]; then
  IS_BUNDLED=1
  PY="${BUNDLED_PY}"
  export MONEYWIZ_TOOLS_HOST="${BUNDLE_HOST}"
elif [[ -e "${BUNDLE_HOST}" ]]; then
  echo "Error: bundled Python runtime is incomplete at ${BUNDLED_PY}." >&2
  echo "Run: make install" >&2
  exit 1
else
  if ! command -v uv >/dev/null 2>&1; then
    echo "Error: 'uv' is not installed." >&2
    echo "Install uv or run 'make install' to use the bundled runtime." >&2
    exit 127
  fi
  export UV_CACHE_DIR="${SCRIPT_DIR}/.uv-cache"
  mkdir -p "${UV_CACHE_DIR}"
  DEV_VENV="${SCRIPT_DIR}/.venv"
  uv sync --project "${SCRIPT_DIR}" --frozen --no-dev
  if [[ ! -x "${DEV_VENV}/bin/python" ]]; then
    echo "Error: uv did not create the project environment at ${DEV_VENV}." >&2
    exit 1
  fi
  PY="${DEV_VENV}/bin/python"
fi

DB_PATH="${CONFIG_DB_PATH:-${DEFAULT_DB_PATH}}"

run_python_script() {
  local script_path="$1"
  shift
  "${PY}" -B -c '
import os
import runpy
import sys

script_path = sys.argv[1]
script_directory = os.path.dirname(os.path.abspath(script_path))
if script_directory not in sys.path:
    sys.path.insert(0, script_directory)
sys.argv = [script_path, *sys.argv[2:]]
try:
    runpy.run_path(script_path, run_name="__main__")
except KeyboardInterrupt:
    raise SystemExit(130)
' "${script_path}" "$@"
}

usage() {
  cat <<USAGE
Usage: moneywiz [--db PATH] <command> [options]

Global:
  --db PATH                           Override the configured database path
  --setup                             Scaffold ~/.moneywizrc
  --version, -V                       Show the installed tool version
  --help                              Show this help

Reads (support --format table|json; default: table):
  users
  accounts [--user ID]
  categories --user ID [--full-name]
  payees [--user ID] [--sort-by-name]
  tags [--user ID]
  transactions [--account ID] [--until YYYY-MM-DD] [--limit N]
               [--with-categories] [--with-tags]
               [--fields f1,f2,...] [--list-fields] [--all-fields]
  holdings --account ID

Writes (dry-run by default; add --apply to commit):
  reassign-payees-by-id [--from-payee-id ID] [--from-empty-payee]
                        [--empty-desc-target-payee-id ID]
                        [--apply] [--quiet] [--show-plan]
                                      --apply requires a verified Core Data capability.
  merge-duplicate-payees [--apply] [--quiet] [--show-plan]
                         [--fuzzy-map PATH] [--overwrite-fuzzy-map]
                                      Apply is blocked until its capability is verified.

Introspection and misc:
  compatibility [--capability NAME] [--format table|json]
  schema [--out-md PATH] [--out-json PATH]
  summary
  stats [--out DIR]
  record (--id ID | --gid GID)
  shell [--db PATH] [--demo-dump] [--log-level LEVEL]
  create-test-db                       Source checkout only
  sanitize-test-db                     Source checkout only
USAGE
}

GLOBAL_DB=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --db)
      if [[ -n "${2-}" ]]; then
        GLOBAL_DB="$2"
        shift 2
      else
        echo "--db requires a path" >&2
        exit 2
      fi
      ;;
    --setup)
      run_setup
      exit 0
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    --*)
      echo "Unknown global option: $1" >&2
      usage
      exit 2
      ;;
    *)
      break
      ;;
  esac
done

SUBCMD="${1-}"
if [[ -z "${SUBCMD}" || "${SUBCMD}" == "-h" || "${SUBCMD}" == "--help" ]]; then
  usage
  exit 0
fi
shift || true

HELP_REQUESTED=0
for argument in "$@"; do
  if [[ "${argument}" == "--help" || "${argument}" == "-h" ]]; then
    HELP_REQUESTED=1
    break
  fi
done

if [[ "${IS_BUNDLED}" -eq 1 ]]; then
  case "${SUBCMD}" in
    create-test-db|sanitize-test-db)
      echo "Error: ${SUBCMD} is a source-checkout-only development command." >&2
      exit 2
      ;;
    *)
      ;;
  esac
fi

BASE_DB_ARG=(--db "${GLOBAL_DB:-${DB_PATH}}")
if [[ "${HELP_REQUESTED}" -eq 0 && "${SUBCMD}" != "shell" && "${SUBCMD}" != "create-test-db" && "${SUBCMD}" != "sanitize-test-db" ]]; then
  DB_TO_USE="${GLOBAL_DB:-${DB_PATH}}"
  if [[ ! -f "${DB_TO_USE}" ]]; then
    echo "Error: Database file not found: ${DB_TO_USE}" >&2
    echo "- Override with: moneywiz --db /path/to/database.sqlite ${SUBCMD} ..." >&2
    exit 1
  fi
fi

case "${SUBCMD}" in
  shell)
    shell_arguments=("$@")
    if [[ "${HELP_REQUESTED}" -eq 1 ]]; then
      for index in "${!shell_arguments[@]}"; do
        if [[ "${shell_arguments[${index}]}" == "-h" ]]; then
          shell_arguments[index]="--help"
        fi
      done
    fi
    run_python_script "${SCRIPT_DIR}/scripts/run_moneywiz_cli.py" "${GLOBAL_DB:-${DB_PATH}}" "${shell_arguments[@]}"
    ;;
  users|accounts|categories|payees|tags|transactions|holdings|record|stats|summary)
    run_python_script "${SCRIPT_DIR}/scripts/${SUBCMD}.py" "${BASE_DB_ARG[@]}" "$@"
    ;;
  reassign-payees-by-id|merge-duplicate-payees)
    script_name="${SUBCMD//-/_}.py"
    run_python_script "${SCRIPT_DIR}/scripts/${script_name}" "${BASE_DB_ARG[@]}" "$@"
    ;;
  compatibility)
    run_python_script "${SCRIPT_DIR}/scripts/compatibility.py" "${BASE_DB_ARG[@]}" "$@"
    ;;
  create-test-db)
    if [[ "${HELP_REQUESTED}" -eq 1 ]]; then
      echo "Usage: moneywiz create-test-db"
      exit 0
    fi
    source_db="${GLOBAL_DB:-${CONFIG_DB_PATH:-${DEFAULT_REAL_DB_PATH}}}"
    if [[ ! -f "${source_db}" ]]; then
      echo "Error: source database not found: ${source_db}" >&2
      exit 1
    fi
    destination="${SCRIPT_DIR}/tests/test_db.sqlite"
    mkdir -p "${SCRIPT_DIR}/tests"
    cp "${source_db}" "${destination}"
    echo "Created test DB at ${destination} (copied from ${source_db})"
    ;;
  sanitize-test-db)
    if [[ "${HELP_REQUESTED}" -eq 1 ]]; then
      run_python_script "${SCRIPT_DIR}/scripts/sanitize_test_db.py" --help
      exit 0
    fi
    target_db="${SCRIPT_DIR}/tests/test_db.sqlite"
    if [[ ! -f "${target_db}" ]]; then
      echo "Error: ${target_db} does not exist. Seed it first with create-test-db." >&2
      exit 1
    fi
    run_python_script "${SCRIPT_DIR}/scripts/sanitize_test_db.py" --db "${target_db}"
    ;;
  schema)
    if [[ "${IS_BUNDLED}" -eq 1 ]]; then
      schema_output_dir="${XDG_DATA_HOME:-${HOME}/.local/share}/moneywiz-tools/schema"
    else
      schema_output_dir="${SCRIPT_DIR}/doc"
    fi
    out_md="${schema_output_dir}/DB-SCHEMA.md"
    out_json="${schema_output_dir}/schema.json"
    while [[ $# -gt 0 ]]; do
      case "$1" in
        --out-md)
          if [[ -z "${2-}" ]]; then
            echo "Error: --out-md requires a path" >&2
            exit 2
          fi
          out_md="$2"
          shift 2
          ;;
        --out-json)
          if [[ -z "${2-}" ]]; then
            echo "Error: --out-json requires a path" >&2
            exit 2
          fi
          out_json="$2"
          shift 2
          ;;
        --help|-h)
          echo "Usage: moneywiz schema [--out-md PATH] [--out-json PATH]"
          exit 0
          ;;
        *)
          echo "Unknown schema option: $1" >&2
          exit 2
          ;;
      esac
    done
    mkdir -p "$(dirname "${out_md}")" "$(dirname "${out_json}")"
    run_python_script "${SCRIPT_DIR}/scripts/introspect_db.py" --db "${GLOBAL_DB:-${DB_PATH}}" --format md > "${out_md}"
    run_python_script "${SCRIPT_DIR}/scripts/introspect_db.py" --db "${GLOBAL_DB:-${DB_PATH}}" --format json > "${out_json}"
    echo "Schema written to ${out_md} and ${out_json}"
    ;;
  *)
    echo "Unknown command: ${SUBCMD}" >&2
    usage
    exit 2
    ;;
esac
