#!/usr/bin/env bash

# Launch MoneyWiz CLI inside a uv-managed virtual environment.
# - Ensures a local .venv exists
# - Installs runtime dependencies via `uv pip install -r requirements.txt`
# - Runs the CLI with your DB path (overridable as first arg)
#
# Examples:
#   ./uv-run-moneywiz-cli.sh
#   ./uv-run-moneywiz-cli.sh --demo-dump --log-level DEBUG
#   ./uv-run-moneywiz-cli.sh /custom/path/ipadMoneyWiz.sqlite

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Default DB path (test database)
DEFAULT_DB_PATH="${SCRIPT_DIR}/tests/test_db.sqlite"

# Optional config support
CONFIG_FILE_NAME=".moneywizrc"
CONFIG_DB_PATH=""
FORK_REPO_URL="https://github.com/marcomc/moneywiz-api.git"
DEFAULT_REAL_DB_PATH="${HOME}/Library/Containers/com.moneywiz.personalfinance-setapp/Data/Documents/.AppData/ipadMoneyWiz.sqlite"

trim_ws() {
  # Trim leading/trailing whitespace from the provided string
  local s="$1"
  s="${s#"${s%%[![:space:]]*}"}"
  s="${s%"${s##*[![:space:]]}"}"
  printf '%s' "${s}"
}

read_config_file() {
  local file="$1"
  [[ -f "${file}" ]] || return 1
  while IFS= read -r line || [[ -n "${line}" ]]; do
    line="${line%%#*}"
    line=$(trim_ws "${line}")
    [[ -z "${line}" ]] && continue
    [[ "${line}" != *"="* ]] && continue
    local key="${line%%=*}"
    local value="${line#*=}"
    key=$(trim_ws "${key}")
    value=$(trim_ws "${value}")
    if [[ "${value}" == "\""*"\"" && ${#value} -ge 2 ]]; then
      value="${value:1:${#value}-2}"
    elif [[ "${value}" == "'"*"'" && ${#value} -ge 2 ]]; then
      value="${value:1:${#value}-2}"
    fi
    if [[ "${value}" == ~/* ]]; then
      value="${HOME}/${value#~/}"
    fi
    # Bash 3.2 (default on macOS) doesn't support `${var,,}` lowercasing.
    # Use `tr` for portability.
    case "$(printf '%s' "${key}" | tr '[:upper:]' '[:lower:]')" in
      db_path)
        CONFIG_DB_PATH="${value}"
        ;;
      *)
        ;;
    esac
  done <"${file}"
}

generate_home_config() {
  local cfg_path="${HOME}/${CONFIG_FILE_NAME}"
  if [[ -f "${cfg_path}" ]]; then
    echo "Config already exists at ${cfg_path}; leaving as-is."
    return
  fi
  local db_line=""
  local note=""
  if [[ -f "${DEFAULT_REAL_DB_PATH}" ]]; then
    db_line="db_path=${DEFAULT_REAL_DB_PATH}"
  else
    db_line="# db_path=${DEFAULT_REAL_DB_PATH}"
    note="# (DB not found; update this path and uncomment once your MoneyWiz DB exists.)"
  fi
  {
    echo "# Moneywiz Tools configuration generated by --setup"
    echo "${db_line}"
    if [[ -n "${note}" ]]; then
      echo "${note}"
    fi
  } > "${cfg_path}"
  echo "Wrote ${cfg_path}"
}

run_setup() {
  local repo_dir="${SCRIPT_DIR}/moneywiz-api"
  if [[ -d "${repo_dir}/.git" ]]; then
    echo "moneywiz-api already present at ${repo_dir}"
  else
    echo "Cloning moneywiz-api fork from ${FORK_REPO_URL}"
    git clone "${FORK_REPO_URL}" "${repo_dir}"
  fi
  generate_home_config
  echo "Setup complete."
}

HOME_CONFIG_FILE="${HOME}/${CONFIG_FILE_NAME}"
LOCAL_CONFIG_FILE="${SCRIPT_DIR}/${CONFIG_FILE_NAME}"

if [[ -z "${CONFIG_DB_PATH}" ]] && [[ -f "${HOME_CONFIG_FILE}" ]]; then
  read_config_file "${HOME_CONFIG_FILE}"
fi

if [[ -z "${CONFIG_DB_PATH}" ]] && [[ -f "${LOCAL_CONFIG_FILE}" ]]; then
  read_config_file "${LOCAL_CONFIG_FILE}"
fi

# Default DB path used unless overridden via global --db
DB_PATH="${CONFIG_DB_PATH:-${DEFAULT_DB_PATH}}"

# Use local uv cache dir to avoid permission issues
export UV_CACHE_DIR="${SCRIPT_DIR}/.uv-cache"
mkdir -p "${UV_CACHE_DIR}"

# Require uv
if ! command -v uv >/dev/null 2>&1; then
  echo "Error: 'uv' is not installed." >&2
  echo "Install uv (see https://docs.astral.sh/uv/getting-started/), e.g.:" >&2
  echo "  curl -LsSf https://astral.sh/uv/install.sh | sh" >&2
  exit 127
fi

# Create or reuse local venv
VENV_DIR="${SCRIPT_DIR}/.venv"
PY_REQ="3.11"
if [[ ! -d "${VENV_DIR}" ]]; then
  uv venv --python "${PY_REQ}" "${VENV_DIR}"
else
  # Recreate venv if Python version is too old (< 3.11)
  if ! "${VENV_DIR}/bin/python" - <<'PY'
import sys
sys.exit(0 if sys.version_info >= (3, 11) else 1)
PY
  then
    echo "Refreshing virtualenv with Python ${PY_REQ} (found older Python)."
    rm -rf "${VENV_DIR}"
    uv venv --python "${PY_REQ}" "${VENV_DIR}"
  fi
fi

# Install runtime deps
if [[ -f "${SCRIPT_DIR}/requirements.txt" ]]; then
  uv pip install -r "${SCRIPT_DIR}/requirements.txt" --python "${VENV_DIR}/bin/python"
fi

# PYTHONPATH to use local source tree directly
export PYTHONPATH="${SCRIPT_DIR}/moneywiz-api/src${PYTHONPATH:+:${PYTHONPATH}}"

usage() {
  cat <<USAGE
Usage: ./moneywiz.sh [--db PATH] <command> [options]

Global:
  --db PATH                           Override database path (default: tests/test_db.sqlite)
  --setup                             Clone moneywiz-api fork and scaffold ~/.moneywizrc
  --help                              Show this help

Reads (support --format table|json; default: table):
  users                               List users
  accounts [--user ID]                List accounts (optionally for user)
  categories --user ID [--full-name]  List categories for user
  payees [--user ID] [--sort-by-name] List payees (optionally for user); sort by name A→Z
  tags [--user ID]                    List tags (optionally for user)
  transactions [--account ID] [--until YYYY-MM-DD] [--limit N]
               [--with-categories] [--with-tags]
               [--fields f1,f2,...] [--list-fields] [--all-fields]
                                      List transactions; omit --account to list across all accounts.
                                      Use '--list-fields' to discover selectable fields for '--fields'.
  holdings --account ID               List investment holdings for an account

Writes (dry-run by default; add --apply to commit):
  insert --type TYPE --fields '{JSON cols}'
  update --id ID --fields '{JSON cols}'
  delete --id ID
  safe-delete --id ID                 Abort if referenced; prints references
  rename --id ID --name NAME [--name-field COL]
  assign-categories --tx ID --splits '[ [cat_id, amount], ... ]'
  assign-tags --tx ID --tags '[ tag_id, ... ]'
  link-refund --refund ID --withdraw ID
  reassign-payees-by-id --from-payee-id ID [--apply] [--quiet] [--show-plan]
                                      Reassign transactions referencing a payee id so that each transaction
                                      references a payee named exactly as its description.

Introspection & Misc:
  schema [--out-md PATH] [--out-json PATH]
                                      Generate Markdown and JSON schema dumps
  summary                             Show counts per manager
  stats [--out DIR]                   Write simple stats snapshots to files
  record (--id ID | --gid GID)        View a record by id or gid
  shell [--db PATH] [--demo-dump] [--log-level LEVEL]
                                      Launch interactive shell (moneywiz-cli)
  create-test-db                      Copy the selected MoneyWiz DB into tests/test_db.sqlite
  sanitize-test-db                    Scrub/anonymize tests/test_db.sqlite

USAGE
}

# Parse optional global --db PATH (must come before subcommand)
GLOBAL_DB=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --db)
      if [[ -n "${2-}" ]]; then GLOBAL_DB="$2"; shift 2; else echo "--db requires a path" >&2; exit 2; fi ;;
    --setup)
      run_setup; exit 0 ;;
    --help|-h)
      usage; exit 0 ;;
    --*)
      echo "Unknown global option: $1" >&2; usage; exit 2 ;;
    *)
      break ;;
  esac
done

SUBCMD="${1-}"
if [[ -z "${SUBCMD}" || "${SUBCMD}" == "-h" || "${SUBCMD}" == "--help" ]]; then
  usage; exit 0
fi
shift || true

# Compose base python and db args for scripts
PY="${VENV_DIR}/bin/python"
BASE_DB_ARG=( )
if [[ -n "${GLOBAL_DB}" ]]; then BASE_DB_ARG=("--db" "${GLOBAL_DB}"); else BASE_DB_ARG=("--db" "${DB_PATH}"); fi


# Validate DB path for subcommands that need it (all except 'shell' when --help)
if [[ "${SUBCMD}" != "shell" ]]; then
  DB_TO_USE="${GLOBAL_DB:-${DB_PATH}}"
  if [[ ! -f "${DB_TO_USE}" ]]; then
    echo "Error: Database file not found: ${DB_TO_USE}" >&2
    echo "- Override with: ./moneywiz.sh --db /path/to/ipadMoneyWiz.sqlite ${SUBCMD} ..." >&2
    exit 1
  fi
fi

case "${SUBCMD}" in
  shell)
    DB_FOR_SHELL="${GLOBAL_DB:-${DB_PATH}}"
    exec "${PY}" "${SCRIPT_DIR}/scripts/run_moneywiz_cli.py" "${DB_FOR_SHELL}" "$@" ;;
  users)
    exec "${PY}" "${SCRIPT_DIR}/scripts/users.py" "${BASE_DB_ARG[@]}" "$@" ;;
  accounts)
    exec "${PY}" "${SCRIPT_DIR}/scripts/accounts.py" "${BASE_DB_ARG[@]}" "$@" ;;
  categories)
    exec "${PY}" "${SCRIPT_DIR}/scripts/categories.py" "${BASE_DB_ARG[@]}" "$@" ;;
  payees)
    exec "${PY}" "${SCRIPT_DIR}/scripts/payees.py" "${BASE_DB_ARG[@]}" "$@" ;;
  tags)
    exec "${PY}" "${SCRIPT_DIR}/scripts/tags.py" "${BASE_DB_ARG[@]}" "$@" ;;
  transactions)
    exec "${PY}" "${SCRIPT_DIR}/scripts/transactions.py" "${BASE_DB_ARG[@]}" "$@" ;;
  holdings)
    exec "${PY}" "${SCRIPT_DIR}/scripts/holdings.py" "${BASE_DB_ARG[@]}" "$@" ;;
  record)
    exec "${PY}" "${SCRIPT_DIR}/scripts/record.py" "${BASE_DB_ARG[@]}" "$@" ;;
  stats)
    exec "${PY}" "${SCRIPT_DIR}/scripts/stats.py" "${BASE_DB_ARG[@]}" "$@" ;;
  summary)
    exec "${PY}" "${SCRIPT_DIR}/scripts/summary.py" "${BASE_DB_ARG[@]}" "$@" ;;
  insert)
    exec "${PY}" "${SCRIPT_DIR}/scripts/insert.py" "${BASE_DB_ARG[@]}" "$@" ;;
  update)
    exec "${PY}" "${SCRIPT_DIR}/scripts/update.py" "${BASE_DB_ARG[@]}" "$@" ;;
  delete)
    exec "${PY}" "${SCRIPT_DIR}/scripts/delete.py" "${BASE_DB_ARG[@]}" "$@" ;;
  safe-delete)
    exec "${PY}" "${SCRIPT_DIR}/scripts/safe_delete.py" "${BASE_DB_ARG[@]}" "$@" ;;
  rename)
    exec "${PY}" "${SCRIPT_DIR}/scripts/rename.py" "${BASE_DB_ARG[@]}" "$@" ;;
  assign-categories)
    exec "${PY}" "${SCRIPT_DIR}/scripts/assign_categories.py" "${BASE_DB_ARG[@]}" "$@" ;;
  assign-tags)
    exec "${PY}" "${SCRIPT_DIR}/scripts/assign_tags.py" "${BASE_DB_ARG[@]}" "$@" ;;
  link-refund)
    exec "${PY}" "${SCRIPT_DIR}/scripts/link_refund.py" "${BASE_DB_ARG[@]}" "$@" ;;
  reassign-payees-by-id)
    exec "${PY}" "${SCRIPT_DIR}/scripts/reassign_payees_by_id.py" "${BASE_DB_ARG[@]}" "$@" ;;
  create-test-db)
    SRC="${GLOBAL_DB}"
    if [[ -z "${SRC}" ]]; then SRC="${CONFIG_DB_PATH}"; fi
    if [[ -z "${SRC}" ]]; then SRC="${DEFAULT_REAL_DB_PATH}"; fi
    if [[ -z "${SRC}" ]]; then
      echo "Error: no source DB could be determined. Pass --db PATH or configure db_path in .moneywizrc." >&2
      exit 1
    fi
    if [[ ! -f "${SRC}" ]]; then
      echo "Error: source database not found: ${SRC}" >&2
      exit 1
    fi
    DEST="${SCRIPT_DIR}/tests/test_db.sqlite"
    mkdir -p "${SCRIPT_DIR}/tests"
    cp "${SRC}" "${DEST}"
    echo "Created test DB at ${DEST} (copied from ${SRC})"
    exit 0 ;;
  sanitize-test-db)
    TARGET_DB="${SCRIPT_DIR}/tests/test_db.sqlite"
    if [[ ! -f "${TARGET_DB}" ]]; then
      echo "Error: ${TARGET_DB} does not exist. Seed it first with create-test-db." >&2
      exit 1
    fi
    exec "${PY}" "${SCRIPT_DIR}/scripts/sanitize_test_db.py" --db "${TARGET_DB}" ;;
  schema)
    # Options: --out-md PATH, --out-json PATH
    OUT_MD="${SCRIPT_DIR}/doc/DB-SCHEMA.md"
    OUT_JSON="${SCRIPT_DIR}/doc/schema.json"
    while [[ $# -gt 0 ]]; do
      case "$1" in
        --out-md)
          OUT_MD="$2"; shift 2 ;;
        --out-json)
          OUT_JSON="$2"; shift 2 ;;
        --help|-h)
          echo "Usage: ./moneywiz.sh schema [--out-md PATH] [--out-json PATH]"; exit 0 ;;
        *)
          echo "Unknown schema option: $1" >&2; exit 2 ;;
      esac
    done
    mkdir -p "$(dirname "${OUT_MD}")" "$(dirname "${OUT_JSON}")"
    DB_TO_USE="${GLOBAL_DB:-${DB_PATH}}"
    "${PY}" "${SCRIPT_DIR}/scripts/introspect_db.py" --db "${DB_TO_USE}" --format md > "${OUT_MD}"
    "${PY}" "${SCRIPT_DIR}/scripts/introspect_db.py" --db "${DB_TO_USE}" --format json > "${OUT_JSON}"
    echo "Schema written to ${OUT_MD} and ${OUT_JSON}"
    ;;
  *)
    echo "Unknown command: ${SUBCMD}" >&2; usage; exit 2 ;;
esac
