#!/usr/bin/env bash

set -euo pipefail

resolve_script_path() {
  local source="$1"
  local directory=""
  local target=""
  while [[ -h "${source}" ]]; do
    directory="$(cd -P "$(dirname "${source}")" && pwd)"
    target="$(/usr/bin/readlink "${source}")"
    if [[ "${target}" == /* ]]; then
      source="${target}"
    else
      source="${directory}/${target}"
    fi
  done
  printf '%s' "${source}"
}

SOURCE_PATH="$(resolve_script_path "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(cd -P "$(dirname "${SOURCE_PATH}")" && pwd)"

DEFAULT_DB_PATH="${SCRIPT_DIR}/tests/test_db.sqlite"
CONFIG_FILE_NAME=".moneywizrc"
CONFIG_DB_PATH=""
FORK_REPO_URL="https://github.com/marcomc/moneywiz-api.git"
DEFAULT_REAL_DB_PATH="${HOME}/Library/Containers/com.moneywiz.personalfinance-setapp/Data/Documents/.AppData/ipadMoneyWiz.sqlite"
BUNDLE_HOST="${SCRIPT_DIR}/../../MacOS/MoneyWizTools"
BUNDLED_PY="${SCRIPT_DIR}/python/venv/bin/python"
BUNDLE_INFO_PLIST="${SCRIPT_DIR}/../Info.plist"
SOURCE_INFO_PLIST="${SCRIPT_DIR}/scripts/MoneyWizTools-Info.plist"

print_version() {
  local info_plist="${BUNDLE_INFO_PLIST}"
  local version=""
  if [[ ! -r "${info_plist}" ]]; then
    info_plist="${SOURCE_INFO_PLIST}"
  fi
  if [[ -r "${info_plist}" ]]; then
    version="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "${info_plist}" 2>/dev/null || true)"
  fi
  printf 'moneywiz %s\n' "${version:-unknown}"
}

for argument in "$@"; do
  if [[ "${argument}" == "--version" || "${argument}" == "-V" ]]; then
    print_version
    exit 0
  fi
done

trim_ws() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "${value}"
}

read_config_file() {
  local file="$1"
  [[ -f "${file}" ]] || return 1
  while IFS= read -r line || [[ -n "${line}" ]]; do
    line="${line%%#*}"
    line="$(trim_ws "${line}")"
    [[ -z "${line}" || "${line}" != *"="* ]] && continue
    local key="${line%%=*}"
    local value="${line#*=}"
    key="$(trim_ws "${key}")"
    value="$(trim_ws "${value}")"
    if [[ "${value}" == \"*\" && ${#value} -ge 2 ]]; then
      value="${value:1:${#value}-2}"
    elif [[ "${value}" == \'*\' && ${#value} -ge 2 ]]; then
      value="${value:1:${#value}-2}"
    fi
    if [[ "${value}" == \~/* ]]; then
      value="${HOME}/${value:2}"
    fi
    case "$(printf '%s' "${key}" | tr '[:upper:]' '[:lower:]')" in
      db_path)
        CONFIG_DB_PATH="${value}"
        ;;
      *)
        ;;
    esac
  done <"${file}"
}

generate_home_config() {
  local config_path="${HOME}/${CONFIG_FILE_NAME}"
  if [[ -f "${config_path}" ]]; then
    echo "Config already exists at ${config_path}; leaving as-is."
    return
  fi
  local db_line=""
  local note=""
  if [[ -f "${DEFAULT_REAL_DB_PATH}" ]]; then
    db_line="db_path=${DEFAULT_REAL_DB_PATH}"
  else
    db_line="# db_path=${DEFAULT_REAL_DB_PATH}"
    note="# Update this path and uncomment it once the database exists."
  fi
  {
    echo "# MoneyWiz Tools configuration generated by --setup"
    echo "${db_line}"
    [[ -n "${note}" ]] && echo "${note}"
  } >"${config_path}"
  echo "Wrote ${config_path}"
}

run_setup() {
  local repo_dir="${SCRIPT_DIR}/moneywiz-api"
  if [[ -x "${BUNDLE_HOST}" ]]; then
    echo "MoneyWiz Tools is already self-contained at ${SCRIPT_DIR}."
  elif [[ -d "${repo_dir}/.git" ]]; then
    echo "moneywiz-api already present at ${repo_dir}"
  else
    echo "Cloning moneywiz-api fork from ${FORK_REPO_URL}"
    git clone "${FORK_REPO_URL}" "${repo_dir}"
  fi
  generate_home_config
  echo "Setup complete."
}

HOME_CONFIG_FILE="${HOME}/${CONFIG_FILE_NAME}"
LOCAL_CONFIG_FILE="${SCRIPT_DIR}/${CONFIG_FILE_NAME}"
if [[ -f "${HOME_CONFIG_FILE}" ]]; then
  read_config_file "${HOME_CONFIG_FILE}"
fi
if [[ -z "${CONFIG_DB_PATH}" && -f "${LOCAL_CONFIG_FILE}" ]]; then
  read_config_file "${LOCAL_CONFIG_FILE}"
fi

if [[ -x "${BUNDLED_PY}" ]]; then
  PY="${BUNDLED_PY}"
  export MONEYWIZ_TOOLS_HOST="${BUNDLE_HOST}"
elif [[ -e "${BUNDLE_HOST}" ]]; then
  echo "Error: bundled Python runtime is incomplete at ${BUNDLED_PY}." >&2
  echo "Run: make install" >&2
  exit 1
else
  if ! command -v uv >/dev/null 2>&1; then
    echo "Error: 'uv' is not installed." >&2
    echo "Install uv or run 'make install' to use the bundled runtime." >&2
    exit 127
  fi
  export UV_CACHE_DIR="${SCRIPT_DIR}/.uv-cache"
  mkdir -p "${UV_CACHE_DIR}"
  DEV_VENV="${SCRIPT_DIR}/.venv"
  if [[ ! -d "${DEV_VENV}" ]]; then
    uv venv --python 3.11 "${DEV_VENV}"
  elif ! "${DEV_VENV}/bin/python" - <<'PY'
import sys
raise SystemExit(sys.version_info[:2] != (3, 11))
PY
  then
    uv venv --clear --python 3.11 "${DEV_VENV}"
  fi
  uv pip install -r "${SCRIPT_DIR}/requirements.txt" --python "${DEV_VENV}/bin/python"
  PY="${DEV_VENV}/bin/python"
fi

export PYTHONPATH="${SCRIPT_DIR}/moneywiz-api/src${PYTHONPATH:+:${PYTHONPATH}}"
DB_PATH="${CONFIG_DB_PATH:-${DEFAULT_DB_PATH}}"

run_python_script() {
  local script_path="$1"
  shift
  "${PY}" -c '
import os
import runpy
import sys

script_path = sys.argv[1]
script_directory = os.path.dirname(os.path.abspath(script_path))
if script_directory not in sys.path:
    sys.path.insert(0, script_directory)
sys.argv = [script_path, *sys.argv[2:]]
try:
    runpy.run_path(script_path, run_name="__main__")
except KeyboardInterrupt:
    raise SystemExit(130)
' "${script_path}" "$@"
}

usage() {
  cat <<USAGE
Usage: moneywiz [--db PATH] <command> [options]

Global:
  --db PATH                           Override the configured database path
  --setup                             Scaffold ~/.moneywizrc
  --version, -V                       Show the installed tool version
  --help                              Show this help

Reads (support --format table|json; default: table):
  users
  accounts [--user ID]
  categories --user ID [--full-name]
  payees [--user ID] [--sort-by-name]
  tags [--user ID]
  transactions [--account ID] [--until YYYY-MM-DD] [--limit N]
               [--with-categories] [--with-tags]
               [--fields f1,f2,...] [--list-fields] [--all-fields]
  holdings --account ID

Writes (dry-run by default; add --apply to commit):
  insert --type TYPE --fields '{JSON cols}'
  update --id ID --fields '{JSON cols}'
  delete --id ID
  safe-delete --id ID
  rename --id ID --name NAME [--name-field COL]
  assign-categories --tx ID --splits '[ [cat_id, amount], ... ]'
  assign-tags --tx ID --tags '[ tag_id, ... ]'
  link-refund --refund ID --withdraw ID
  reassign-payees-by-id [--from-payee-id ID] [--from-empty-payee]
                        [--empty-desc-target-payee-id ID]
                        [--apply] [--quiet] [--show-plan]
                                      --apply uses the bundled Core Data host.
                                      Quit MoneyWiz before applying, then reopen it.
  merge-duplicate-payees [--apply] [--quiet] [--show-plan]
                         [--fuzzy-map PATH] [--overwrite-fuzzy-map]
                                      Merges exact-normalized groups through the
                                      bundled Core Data host. Similar pairs are
                                      exported for manual approval only.

Introspection and misc:
  schema [--out-md PATH] [--out-json PATH]
  summary
  stats [--out DIR]
  record (--id ID | --gid GID)
  shell [--db PATH] [--demo-dump] [--log-level LEVEL]
  create-test-db
  sanitize-test-db
USAGE
}

GLOBAL_DB=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --db)
      if [[ -n "${2-}" ]]; then
        GLOBAL_DB="$2"
        shift 2
      else
        echo "--db requires a path" >&2
        exit 2
      fi
      ;;
    --setup)
      run_setup
      exit 0
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    --*)
      echo "Unknown global option: $1" >&2
      usage
      exit 2
      ;;
    *)
      break
      ;;
  esac
done

SUBCMD="${1-}"
if [[ -z "${SUBCMD}" || "${SUBCMD}" == "-h" || "${SUBCMD}" == "--help" ]]; then
  usage
  exit 0
fi
shift || true

BASE_DB_ARG=(--db "${GLOBAL_DB:-${DB_PATH}}")
if [[ "${SUBCMD}" != "shell" ]]; then
  DB_TO_USE="${GLOBAL_DB:-${DB_PATH}}"
  if [[ ! -f "${DB_TO_USE}" ]]; then
    echo "Error: Database file not found: ${DB_TO_USE}" >&2
    echo "- Override with: moneywiz --db /path/to/database.sqlite ${SUBCMD} ..." >&2
    exit 1
  fi
fi

case "${SUBCMD}" in
  shell)
    run_python_script "${SCRIPT_DIR}/scripts/run_moneywiz_cli.py" "${GLOBAL_DB:-${DB_PATH}}" "$@"
    ;;
  users|accounts|categories|payees|tags|transactions|holdings|record|stats|summary)
    run_python_script "${SCRIPT_DIR}/scripts/${SUBCMD}.py" "${BASE_DB_ARG[@]}" "$@"
    ;;
  insert|update|delete|safe-delete|rename)
    script_name="${SUBCMD//-/_}.py"
    run_python_script "${SCRIPT_DIR}/scripts/${script_name}" "${BASE_DB_ARG[@]}" "$@"
    ;;
  assign-categories|assign-tags|link-refund|reassign-payees-by-id|merge-duplicate-payees)
    script_name="${SUBCMD//-/_}.py"
    run_python_script "${SCRIPT_DIR}/scripts/${script_name}" "${BASE_DB_ARG[@]}" "$@"
    ;;
  create-test-db)
    source_db="${GLOBAL_DB:-${CONFIG_DB_PATH:-${DEFAULT_REAL_DB_PATH}}}"
    if [[ ! -f "${source_db}" ]]; then
      echo "Error: source database not found: ${source_db}" >&2
      exit 1
    fi
    destination="${SCRIPT_DIR}/tests/test_db.sqlite"
    mkdir -p "${SCRIPT_DIR}/tests"
    cp "${source_db}" "${destination}"
    echo "Created test DB at ${destination} (copied from ${source_db})"
    ;;
  sanitize-test-db)
    target_db="${SCRIPT_DIR}/tests/test_db.sqlite"
    if [[ ! -f "${target_db}" ]]; then
      echo "Error: ${target_db} does not exist. Seed it first with create-test-db." >&2
      exit 1
    fi
    run_python_script "${SCRIPT_DIR}/scripts/sanitize_test_db.py" --db "${target_db}"
    ;;
  schema)
    out_md="${SCRIPT_DIR}/doc/DB-SCHEMA.md"
    out_json="${SCRIPT_DIR}/doc/schema.json"
    while [[ $# -gt 0 ]]; do
      case "$1" in
        --out-md)
          out_md="$2"
          shift 2
          ;;
        --out-json)
          out_json="$2"
          shift 2
          ;;
        --help|-h)
          echo "Usage: moneywiz schema [--out-md PATH] [--out-json PATH]"
          exit 0
          ;;
        *)
          echo "Unknown schema option: $1" >&2
          exit 2
          ;;
      esac
    done
    mkdir -p "$(dirname "${out_md}")" "$(dirname "${out_json}")"
    run_python_script "${SCRIPT_DIR}/scripts/introspect_db.py" --db "${GLOBAL_DB:-${DB_PATH}}" --format md > "${out_md}"
    run_python_script "${SCRIPT_DIR}/scripts/introspect_db.py" --db "${GLOBAL_DB:-${DB_PATH}}" --format json > "${out_json}"
    echo "Schema written to ${out_md} and ${out_json}"
    ;;
  *)
    echo "Unknown command: ${SUBCMD}" >&2
    usage
    exit 2
    ;;
esac
